export const MODELED_RECOVERY_ASSUMPTION_RATE = 0.62;
export const MODELED_RECOVERY_ASSUMPTION_PERCENT =
  Math.round(MODELED_RECOVERY_ASSUMPTION_RATE * 100) + "%";
export const RECOVERY_MODEL_UPDATED = "July 2026";
