/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BenchmarkRouteImport } from './routes/benchmark'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardBenchmarkRouteImport } from './routes/dashboard.benchmark'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as DashboardSequencesRouteImport } from './routes/_dashboard/sequences'
import { Route as DashboardPaymentsRouteImport } from './routes/_dashboard/payments'
import { Route as DashboardEscalationsRouteImport } from './routes/_dashboard/escalations'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as DashboardAlertsRouteImport } from './routes/_dashboard/alerts'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiStripeDisconnectRouteImport } from './routes/api/stripe/disconnect'
import { Route as ApiStripeConnectRouteImport } from './routes/api/stripe/connect'
import { Route as ApiStripeCallbackRouteImport } from './routes/api/stripe/callback'
import { Route as ApiCronProcessEmailsRouteImport } from './routes/api/cron/process-emails'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardPaymentsIdRouteImport } from './routes/_dashboard/payments_.$id'
import { Route as ApiStripeWebhookAccountIdRouteImport } from './routes/api/stripe/webhook.$accountId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarkRoute = BenchmarkRouteImport.update({
  id: '/benchmark',
  path: '/benchmark',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBenchmarkRoute = DashboardBenchmarkRouteImport.update({
  id: '/dashboard/benchmark',
  path: '/dashboard/benchmark',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSequencesRoute = DashboardSequencesRouteImport.update({
  id: '/sequences',
  path: '/sequences',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEscalationsRoute = DashboardEscalationsRouteImport.update({
  id: '/escalations',
  path: '/escalations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlertsRoute = DashboardAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeDisconnectRoute = ApiStripeDisconnectRouteImport.update({
  id: '/api/stripe/disconnect',
  path: '/api/stripe/disconnect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeConnectRoute = ApiStripeConnectRouteImport.update({
  id: '/api/stripe/connect',
  path: '/api/stripe/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeCallbackRoute = ApiStripeCallbackRouteImport.update({
  id: '/api/stripe/callback',
  path: '/api/stripe/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronProcessEmailsRoute = ApiCronProcessEmailsRouteImport.update({
  id: '/api/cron/process-emails',
  path: '/api/cron/process-emails',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPaymentsIdRoute = DashboardPaymentsIdRouteImport.update({
  id: '/payments_/$id',
  path: '/payments/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiStripeWebhookAccountIdRoute =
  ApiStripeWebhookAccountIdRouteImport.update({
    id: '/$accountId',
    path: '/$accountId',
    getParentRoute: () => ApiStripeWebhookRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/benchmark': typeof BenchmarkRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/alerts': typeof DashboardAlertsRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/escalations': typeof DashboardEscalationsRoute
  '/payments': typeof DashboardPaymentsRoute
  '/sequences': typeof DashboardSequencesRoute
  '/settings': typeof DashboardSettingsRoute
  '/dashboard/benchmark': typeof DashboardBenchmarkRoute
  '/payments/$id': typeof DashboardPaymentsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/process-emails': typeof ApiCronProcessEmailsRoute
  '/api/stripe/callback': typeof ApiStripeCallbackRoute
  '/api/stripe/connect': typeof ApiStripeConnectRoute
  '/api/stripe/disconnect': typeof ApiStripeDisconnectRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRouteWithChildren
  '/api/stripe/webhook/$accountId': typeof ApiStripeWebhookAccountIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/benchmark': typeof BenchmarkRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/alerts': typeof DashboardAlertsRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/escalations': typeof DashboardEscalationsRoute
  '/payments': typeof DashboardPaymentsRoute
  '/sequences': typeof DashboardSequencesRoute
  '/settings': typeof DashboardSettingsRoute
  '/dashboard/benchmark': typeof DashboardBenchmarkRoute
  '/payments/$id': typeof DashboardPaymentsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/process-emails': typeof ApiCronProcessEmailsRoute
  '/api/stripe/callback': typeof ApiStripeCallbackRoute
  '/api/stripe/connect': typeof ApiStripeConnectRoute
  '/api/stripe/disconnect': typeof ApiStripeDisconnectRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRouteWithChildren
  '/api/stripe/webhook/$accountId': typeof ApiStripeWebhookAccountIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/benchmark': typeof BenchmarkRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_dashboard/alerts': typeof DashboardAlertsRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/escalations': typeof DashboardEscalationsRoute
  '/_dashboard/payments': typeof DashboardPaymentsRoute
  '/_dashboard/sequences': typeof DashboardSequencesRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/benchmark': typeof DashboardBenchmarkRoute
  '/_dashboard/payments_/$id': typeof DashboardPaymentsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/process-emails': typeof ApiCronProcessEmailsRoute
  '/api/stripe/callback': typeof ApiStripeCallbackRoute
  '/api/stripe/connect': typeof ApiStripeConnectRoute
  '/api/stripe/disconnect': typeof ApiStripeDisconnectRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRouteWithChildren
  '/api/stripe/webhook/$accountId': typeof ApiStripeWebhookAccountIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/benchmark'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/signup'
    | '/alerts'
    | '/dashboard'
    | '/escalations'
    | '/payments'
    | '/sequences'
    | '/settings'
    | '/dashboard/benchmark'
    | '/payments/$id'
    | '/api/auth/$'
    | '/api/cron/process-emails'
    | '/api/stripe/callback'
    | '/api/stripe/connect'
    | '/api/stripe/disconnect'
    | '/api/stripe/webhook'
    | '/api/stripe/webhook/$accountId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/benchmark'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/signup'
    | '/alerts'
    | '/dashboard'
    | '/escalations'
    | '/payments'
    | '/sequences'
    | '/settings'
    | '/dashboard/benchmark'
    | '/payments/$id'
    | '/api/auth/$'
    | '/api/cron/process-emails'
    | '/api/stripe/callback'
    | '/api/stripe/connect'
    | '/api/stripe/disconnect'
    | '/api/stripe/webhook'
    | '/api/stripe/webhook/$accountId'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/benchmark'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/signup'
    | '/_dashboard/alerts'
    | '/_dashboard/dashboard'
    | '/_dashboard/escalations'
    | '/_dashboard/payments'
    | '/_dashboard/sequences'
    | '/_dashboard/settings'
    | '/dashboard/benchmark'
    | '/_dashboard/payments_/$id'
    | '/api/auth/$'
    | '/api/cron/process-emails'
    | '/api/stripe/callback'
    | '/api/stripe/connect'
    | '/api/stripe/disconnect'
    | '/api/stripe/webhook'
    | '/api/stripe/webhook/$accountId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  BenchmarkRoute: typeof BenchmarkRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  DashboardBenchmarkRoute: typeof DashboardBenchmarkRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronProcessEmailsRoute: typeof ApiCronProcessEmailsRoute
  ApiStripeCallbackRoute: typeof ApiStripeCallbackRoute
  ApiStripeConnectRoute: typeof ApiStripeConnectRoute
  ApiStripeDisconnectRoute: typeof ApiStripeDisconnectRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmark': {
      id: '/benchmark'
      path: '/benchmark'
      fullPath: '/benchmark'
      preLoaderRoute: typeof BenchmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/benchmark': {
      id: '/dashboard/benchmark'
      path: '/dashboard/benchmark'
      fullPath: '/dashboard/benchmark'
      preLoaderRoute: typeof DashboardBenchmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/sequences': {
      id: '/_dashboard/sequences'
      path: '/sequences'
      fullPath: '/sequences'
      preLoaderRoute: typeof DashboardSequencesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/payments': {
      id: '/_dashboard/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/escalations': {
      id: '/_dashboard/escalations'
      path: '/escalations'
      fullPath: '/escalations'
      preLoaderRoute: typeof DashboardEscalationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/alerts': {
      id: '/_dashboard/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof DashboardAlertsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/disconnect': {
      id: '/api/stripe/disconnect'
      path: '/api/stripe/disconnect'
      fullPath: '/api/stripe/disconnect'
      preLoaderRoute: typeof ApiStripeDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/connect': {
      id: '/api/stripe/connect'
      path: '/api/stripe/connect'
      fullPath: '/api/stripe/connect'
      preLoaderRoute: typeof ApiStripeConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/callback': {
      id: '/api/stripe/callback'
      path: '/api/stripe/callback'
      fullPath: '/api/stripe/callback'
      preLoaderRoute: typeof ApiStripeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/process-emails': {
      id: '/api/cron/process-emails'
      path: '/api/cron/process-emails'
      fullPath: '/api/cron/process-emails'
      preLoaderRoute: typeof ApiCronProcessEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/payments_/$id': {
      id: '/_dashboard/payments_/$id'
      path: '/payments/$id'
      fullPath: '/payments/$id'
      preLoaderRoute: typeof DashboardPaymentsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/stripe/webhook/$accountId': {
      id: '/api/stripe/webhook/$accountId'
      path: '/$accountId'
      fullPath: '/api/stripe/webhook/$accountId'
      preLoaderRoute: typeof ApiStripeWebhookAccountIdRouteImport
      parentRoute: typeof ApiStripeWebhookRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAlertsRoute: typeof DashboardAlertsRoute
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardEscalationsRoute: typeof DashboardEscalationsRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardSequencesRoute: typeof DashboardSequencesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardPaymentsIdRoute: typeof DashboardPaymentsIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAlertsRoute: DashboardAlertsRoute,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardEscalationsRoute: DashboardEscalationsRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardSequencesRoute: DashboardSequencesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardPaymentsIdRoute: DashboardPaymentsIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ApiStripeWebhookRouteChildren {
  ApiStripeWebhookAccountIdRoute: typeof ApiStripeWebhookAccountIdRoute
}

const ApiStripeWebhookRouteChildren: ApiStripeWebhookRouteChildren = {
  ApiStripeWebhookAccountIdRoute: ApiStripeWebhookAccountIdRoute,
}

const ApiStripeWebhookRouteWithChildren =
  ApiStripeWebhookRoute._addFileChildren(ApiStripeWebhookRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  BenchmarkRoute: BenchmarkRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  DashboardBenchmarkRoute: DashboardBenchmarkRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronProcessEmailsRoute: ApiCronProcessEmailsRoute,
  ApiStripeCallbackRoute: ApiStripeCallbackRoute,
  ApiStripeConnectRoute: ApiStripeConnectRoute,
  ApiStripeDisconnectRoute: ApiStripeDisconnectRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
